### PR TITLE
Upgrade to AspNetCore 2.1

### PR DESCRIPTION
**Pull request by pentp**
* Upgrade all projects to AspNetCore 2.1
* Remove WebListener
* Remove netframework projects/targets, leave only netstandard2.0
* Use async methods for WebHost starting/stopping

### CODE REVIEW

**Comment by amanbha** [comment]
@pentp Thanks for the changes but we cant remove support for that as customers are still using AspNetcore 1.* and lower versions of full frameworks.
cc @masnider

**Comment by juho-hanhimaki** [comment]
.NET Core 1.* is officially out of support per .NET Core Support Policy (https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

I don't see point in supporting unsupported framework versions. That is like supporting IE6 because somebody still uses it.

**Comment by pentp** [comment]
As @juho-hanhimaki pointed out, AspNetCore 1.* and .NET Core 1.* are out of support. Existing customers can continue using them but I see no reason to support them in newer versions of this project's nuget packages.
As AspNetCore 2.0 requires netstandard2.0 anyway, there is no need for separate full framework packages (the packages will work with .NET Framework 4.6.1+).

**Comment by amanbha** [comment]
@pentp 
There are following changes been made in this PR:
1. Referencing asp netcore 2..0 binaries, which drops support for aspnetcore 1.*
2. Building for netstandard 2.0 which drops support for netfx <4.6.1
3. Dropping support for WebListener.

While 1 above can be done, 2 & 3 cant be done as there are customers using WebListener and deploying apps built against netfx <4.6.1.
Even for doing 1, it needs to be mentioned in SF release notes first, before pulling the plug on it.

cc @masnider  as well.

**Comment by juho-hanhimaki** [comment]
WebListener was renamed to HttpSys (as it is known as http.sys in Windows) in ASP.NET Core 2. There should indeed be no reason to remove support for it (if it was the intention of this PR)?

**Comment by pentp** [comment]
Microsoft.ServiceFabric.AspNetCore.HttpSys project/package is still here, so nothing is removed (other than 1.* support).

**Comment by pentp** [comment]
> While 1 above can be done, 2 & 3 cant be done as there are customers using WebListener and deploying apps built against netfx <4.6.1.

1 implies 2 & 3 as AspNetCore 2.0 requires netstandard2.0 (and WebListener was just renamed to HttpSys in 2.0).

To put it another way: using WebListener and/or building against netfx <4.6.1 is not possible with AspNetCore 2.0

**Comment by amanbha** [comment]
@pentp  I fully agree that change is well intentioned and is the right thing to do and reduces the support matrix,, but since these are breaking and customers depend on it, it would need enough forewarning given to customers about:
1. Drops support for aspnetcore 1.*
2. Drop support for netfx <4.6.1
3. Not shipping a WebListener. nupkg(HttpSys will cover it)

We will add it to SF release notes and then make the changes in a subsequent release.

**Comment by amanbha** [comment]
@pentp Even 2.0 is out of support, we can build against 2.1

**Comment by pentp** [comment]
@amanbha is it now possible to do the upgrade as 7.0 has been out for a while with the documentation for upcoming changes?

**Comment by amanbha** [comment]
> @amanbha is it now possible to do the upgrade as 7.0 has been out for a while with the documentation for upcoming changes?

The release notes mentioned that the changes in the PR will be done in 8.0
https://techcommunity.microsoft.com/t5/azure-service-fabric/service-fabric-7-0-release/ba-p/1015482

So I would take these changes for 8.0 
cc @masnider for timelines around 8.0

**Comment by masnider** [comment]
@sridmad we need to remember to take this and ship with 8.0, and the upcoming changes notifications should start going into relnotes with the next release.

**Comment by pentp** [comment]
From the October newsletter it looks like SF 7.2 will drop .NET Core 2.2 support (which implies that 1.x is also dropped), so this could be included in 7.2 already?

**Pull request merged**
